global:
  # Configuration SMTP (optionnelle - décommenter pour utiliser l'email)
  # smtp_smarthost: 'smtp.gmail.com:587'
  # smtp_from: 'votre-email@gmail.com'
  # smtp_auth_username: 'votre-email@gmail.com'
  # smtp_auth_password: 'votre-mot-de-passe-app'

# Définition des routes pour les alertes
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web-console'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
    repeat_interval: 5m
  - match:
      severity: warning
    receiver: 'warning-alerts'
    repeat_interval: 15m

# Configuration des récepteurs de notifications
receivers:
# Récepteur par défaut - affichage dans la console web AlertManager
- name: 'web-console'

# Récepteur pour les alertes critiques
- name: 'critical-alerts'
  # Exemple de configuration email (décommenter si configuré)
  # email_configs:
  # - to: 'admin@votre-domaine.com'
  #   subject: '🚨 ALERTE CRITIQUE: {{ .GroupLabels.alertname }}'
  #   body: |
  #     🚨 ALERTE CRITIQUE DÉTECTÉE 🚨
  #     
  #     {{ range .Alerts }}
  #     Alerte: {{ .Annotations.summary }}
  #     Description: {{ .Annotations.description }}
  #     Heure: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
  #     
  #     Détails:
  #     {{ range .Labels.SortedPairs }}• {{ .Name }}: {{ .Value }}
  #     {{ end }}
  #     {{ end }}

# Récepteur pour les alertes d'avertissement  
- name: 'warning-alerts'
  # email_configs:
  # - to: 'admin@votre-domaine.com'
  #   subject: '⚠️ Avertissement: {{ .GroupLabels.alertname }}'

# Inhibition des alertes (évite le spam d'alertes)
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'instance'] 