global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@localhost'

# Modèles pour les notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Définition des routes pour les alertes
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
  - match:
      severity: critical
    receiver: 'critical-receiver'
    repeat_interval: 5m
  - match:
      severity: warning
    receiver: 'warning-receiver'
    repeat_interval: 15m

# Configuration des récepteurs de notifications
receivers:
- name: 'default-receiver'
  webhook_configs:
  - url: 'http://localhost:9093/webhook'
    send_resolved: true

- name: 'critical-receiver'
  webhook_configs:
  - url: 'http://localhost:9093/webhook/critical'
    send_resolved: true
    title: 'CRITIQUE: {{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      Alerte: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
      {{ end }}

- name: 'warning-receiver'
  webhook_configs:
  - url: 'http://localhost:9093/webhook/warning'
    send_resolved: true
    title: 'ATTENTION: {{ .GroupLabels.alertname }}'

# Inhibition des alertes (pour éviter le spam)
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service'] 